### ISSUE TITLE
Issue #03 - Schema

### ISSUE THREAD

**Issue by keginzburg** [jacobbenowitz/5000px#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table’s name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
You have a lot of information here. Following the notes below, I would try to streamline a bit, so your schema is clearer.

1. Users Table vs Profile
    1. At this point, you have a lot of information condensed into your Profile table and my main question is whether or not you need all that information or if it factors into bonus material.
    2. Also, is the profile table somewhat redundant as each User only has one profile? Could you add profile information to a user table when they are making an account and forego a Profile table for the time being? Tell me your thoughts in a comment below.
2. Users
    1. You specify email as unique but without an indexed spec below the table.
    2. You specify gender inclusion despite that not being within this table
    3. I would specify through associations as well (I.e. followers through follows, likes (maybe as liked_photos) through photos, etc.
3. Photos
    1. Once again, specify through associations please.
    2. Does a photo have many comments?
4. User Profiles
    1. Assuming you keep two tables to separate your User and Profile, is a joins table necessary for those two tables?
5. User Photos
    1. Again, is a joins table necessary to connect our Users and their Photos?

**Comment by jacobbenowitz** [comment]
@keginzburg, please see my responses below:

1. Users Table vs Profile
- I separated them because users can create an account without completing their profile on the actual 500px site
- Also felt like a good separation of concerns: 
  - the users table = source of truth for user auth, while profiles = source of truth for the profile pages (can be public)
- Also, I feel like the profile data does not need to be on state, only fetched when needed on user show page
2. Users
- Added unique index to email
- Gender inclusion moved to profiles 
- Added through associations
3. Photos
- Yes, I think a photo does have many comments because comments belong to a photo via the photo_id foreign key. Is this the correct approach?
4. User Profiles - removed: not necessary
5. User Photos - removed: not necessary

**Comment by keginzburg** [comment]
Awesome work!
